export const TRANSFER_MONEY = "TRANSFER_MONEY";
// export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const TRANSFER_SUCCESS = "TRANSFER_SUCCESS";
export const TRANSFER_ERROR = "TRANSFER_ERROR";
export const TRANSFER_IN_PROGRESS = "TRANSFER_IN_PROGRESS";
